//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> WaiterID { get; set; }
        public Nullable<System.DateTime> Order_time { get; set; }
        public Nullable<int> MenuID { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Waiter Waiter { get; set; }
        public virtual Client Client { get; set; }
    }
}
